name: Simple Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyse:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 linter
        run: |
          echo "Running code analysis..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  package:
    name: Zip Application Code
    runs-on: ubuntu-latest
    needs: analyse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP package
        run: |
          echo "Packaging application..."
          zip -r app_package.zip .

      - name: Upload package as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_package
          path: app_package.zip
